---
title: "The Hours"
author: "Joanna Prout"
date: "6/16/2021"
output: html_document
---

```{r setup, include=FALSE}
library (tidyverse)

d <- read_csv ("hourlydata.csv")

d$date <- as.Date(d$date, "%m/%d/%y")

d$time <- paste (d$hour, ":00", sep = "")

d$datetime <- as.POSIXct(paste(d$date, d$time), format="%Y-%m-%d %H")


```

```{r}
sm <- d %>%
  select(datetime, mood, anx,overwhelm, lightness, rain, asleep)
```


```{r pivot longer?}
long <- pivot_longer (sm, mood:rain, names_to = "experience",
                      values_to = "value")

#changing NA to 0 seems like a good idea
long[is.na(long)] = 0

```

```{r}
mood <- ggplot(long %>% filter (experience == "mood"), 
               aes (x = datetime, y = value)) +
  geom_area (color = "blue", 
             fill = "blue") 

mood
  
```

```{r}

sleep <- ggplot (long %>% filter (experience == "asleep"),
                    aes (x=datetime, y=value)) +
                    geom_area (fill = "blue")
sleep
```

```{r}
ggplot (data = long, aes (x=datetime, y=value, color = experience, fill = experience))+
  geom_area () +
  geom_line ()
```


```{r}
p <- ggplot() + 
    geom_col(data = long, 
             mapping = aes(x = datetime, 
                           y = asleep)
             ) + 
    xlab("Time") + 
 
    geom_area(data = long %>% 
                filter (experience == "mood"), 
              mapping = aes(x = datetime,
                            y = value),
              fill = "red"
            
              ) +
    theme_bw()
p
```

```{r}
p + ylim (-2,2)
```







```{r}
library (scales)
    p + scale_x_datetime(labels = date_format("%Y-%m-%d %H"),
                     date_breaks = "1 hour") +
      theme (axis.text.x = element_text (angle = 45))+
      coord_cartesian(xlim = ("2021-2020-06-12 10:00:00")
```




